/**
 * @file SSHConfig.cxx
 * @copyright
 * Copyright 2025 LogosITO
 * Licensed under MIT-License
 *
 * @english
 * @brief SSH configuration implementation
 * @details Implementation of SSH configuration methods
 *
 * @russian
 * @brief Реализация SSH конфигурации
 * @details Реализация методов SSH конфигурации
 */

#include "SSHConfig.hxx"
#include <fstream>
#include <sstream>
#include <filesystem>

namespace svcs::server::ssh {

namespace fs = std::filesystem;

SSHConfig SSHConfig::load(const std::string& path) {
    SSHConfig config;
    std::ifstream file(path);
    if (!file) return config;

    std::string line;
    while (std::getline(file, line)) {
        line.erase(0, line.find_first_not_of(" \t"));
        line.erase(line.find_last_not_of(" \t") + 1);

        if (line.empty() || line[0] == '#') continue;

        size_t eq = line.find('=');
        if (eq == std::string::npos) continue;

        std::string key = line.substr(0, eq);
        std::string value = line.substr(eq + 1);

        // Убираем пробелы вокруг ключа и значения
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);

        // Убираем кавычки если есть
        if (!value.empty() && value.front() == '"' && value.back() == '"') {
            value = value.substr(1, value.size() - 2);
        }

        if (key == "host") config.host = value;
        else if (key == "port") config.port = static_cast<uint16_t>(std::stoi(value));
        else if (key == "host_key") config.host_key = value;
        else if (key == "auth_file") config.auth_file = value;
        else if (key == "keys_dir") config.keys_dir = value;
        else if (key == "passwd_dir") config.passwd_dir = value;
        else if (key == "max_connections") config.max_connections = std::stoul(value);
        else if (key == "timeout_sec") config.timeout_sec = std::stoi(value);
    }

    return config;
}

bool SSHConfig::save(const std::string& path) const {
    std::ofstream file(path);
    if (!file) return false;

    file << "# SSH Server Configuration\n";
    file << "# Generated by SVCS\n\n";

    file << "host = " << host << "\n";
    file << "port = " << port << "\n";
    file << "host_key = \"" << host_key << "\"\n";
    file << "auth_file = \"" << auth_file << "\"\n";
    file << "keys_dir = \"" << keys_dir << "\"\n";
    file << "passwd_dir = \"" << passwd_dir << "\"\n";
    file << "max_connections = " << max_connections << "\n";
    file << "timeout_sec = " << timeout_sec << "\n";

    return file.good();
}

bool SSHConfig::validate() const {
    if (host.empty()) return false;
    if (port == 0 || port > 65535) return false;
    if (host_key.empty()) return false;
    if (max_connections == 0) return false;
    if (timeout_sec <= 0) return false;

    return true;
}

}