name: CMake Multi-Platform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Setup Vcpkg and Install Dependencies (Boost & OpenSSL)
      uses: vcpkg-tool/setup-vcpkg@v1
      with:
        token: ${{ github.token }}
        
    - name: Configure CMake
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        # CMAKE_TOOLCHAIN_FILE - ключевой параметр, связывающий CMake и Vcpkg.

    - name: Build Project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel
      
    - name: Run Tests
      run: ctest --test-dir ${{ github.workspace }}/build -C ${{ matrix.build_type }} --output-on-failure
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}-binaries
        path: ${{ github.workspace }}/build/bin/*
