name: CMake Multi-Platform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install System Prerequisites (Robust for Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config m4 linux-libc-dev curl wget tar gzip
        elif [ "${{ runner.os }}" == "macOS" ]; then
          brew install autoconf automake libtool
        fi

    - name: Cache Vcpkg Installed Packages
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg/installed
        key: ${{ runner.os }}-vcpkg-packages-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-packages-
        
    - name: Manually Setup Vcpkg and Install Dependencies (Boost & OpenSSL)
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./vcpkg/bootstrap-vcpkg.bat
        else
          ./vcpkg/bootstrap-vcpkg.sh
        fi
        
        ./vcpkg/vcpkg install

    - name: Configure CMake
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        # CMAKE_TOOLCHAIN_FILE - ключевой параметр, связывающий CMake и Vcpkg.

    - name: Build Project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel
      
    - name: Run Tests
      run: ctest --test-dir ${{ github.workspace }}/build -C ${{ matrix.build_type }} --output-on-failure
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}-binaries
        path: ${{ github.workspace }}/build/bin/*
