name: Deploying Jekyll with GitHub Pages Dependencies Pre-Installed

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure pages
        uses: actions/configure-pages@v5
        
      - name: Creating English pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/en/html
          destination: ./_site/en/ 
      
      - name: Creating Russian pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/ru/html
          destination: ./_site/ru/ 
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload on github pages
        id: deployment
        uses: actions/deploy-pages@v4
